from __future__ import annotations

import json
from pathlib import Path
from threading import Lock

from dotenv import dotenv_values

from backend.app.core.config import AppSettings
from backend.app.models.schemas import ConfigResponse, RuntimeConfig, UpdateConfigRequest


class ConfigStore:
    def __init__(self, path: Path):
        self.path = path
        self._lock = Lock()
        self.path.parent.mkdir(parents=True, exist_ok=True)

    def _read_raw(self) -> dict:
        if not self.path.exists():
            return {}
        try:
            with self.path.open("r", encoding="utf-8") as handle:
                return json.load(handle)
        except json.JSONDecodeError:
            return {}

    def _write_raw(self, payload: dict) -> None:
        with self.path.open("w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2)

    def _runtime_from_saved(self, settings: AppSettings, saved: dict) -> RuntimeConfig:
        defaults = RuntimeConfig(
            confluence_base_url=settings.confluence_base_url,
            confluence_email=settings.confluence_email,
            confluence_api_token=settings.confluence_api_token,
            ollama_base_url=settings.ollama_base_url,
            ollama_model=settings.ollama_model,
        )
        merged = defaults.model_dump()
        for key, value in saved.items():
            if key in merged and value is not None:
                merged[key] = value
        return RuntimeConfig(**merged)

    def effective_config(self, settings: AppSettings) -> RuntimeConfig:
        with self._lock:
            saved = self._read_raw()
        return self._runtime_from_saved(settings, saved)

    def public_config(self, settings: AppSettings) -> ConfigResponse:
        runtime = self.effective_config(settings)
        return ConfigResponse(
            confluence_base_url=runtime.confluence_base_url,
            confluence_email=runtime.confluence_email,
            confluence_api_token_set=bool(runtime.confluence_api_token),
            ollama_base_url=runtime.ollama_base_url,
            ollama_model=runtime.ollama_model,
            mcp_url=settings.resolved_mcp_url(),
            workspace_root=str(settings.workspace_root),
            env_file_path=str(settings.env_file_path),
            env_file_exists=settings.env_file_path.exists(),
        )

    def update(self, settings: AppSettings, update: UpdateConfigRequest) -> ConfigResponse:
        payload = update.model_dump(exclude_none=True)
        with self._lock:
            current = self._read_raw()
            for key, value in payload.items():
                if key == "confluence_api_token" and value == "":
                    continue
                current[key] = value
            self._write_raw(current)
            self._write_env_file(settings, current)
        return self.public_config(settings)

    def _write_env_file(self, settings: AppSettings, saved: dict) -> None:
        runtime = self._runtime_from_saved(settings, saved)
        env_path = settings.env_file_path
        env_path.parent.mkdir(parents=True, exist_ok=True)

        existing_values = {}
        if env_path.exists():
            existing_values = {key: value for key, value in dotenv_values(env_path).items() if value is not None}

        managed_values = {
            "CONFLUENCE_BASE_URL": runtime.confluence_base_url,
            "CONFLUENCE_EMAIL": runtime.confluence_email,
            "CONFLUENCE_API_TOKEN": runtime.confluence_api_token,
            "OLLAMA_BASE_URL": runtime.ollama_base_url,
            "OLLAMA_MODEL": runtime.ollama_model,
            "APP_PORT": str(settings.app_port),
            "MCP_PORT": str(settings.mcp_port),
            "PUBLIC_BACKEND_URL": settings.public_backend_url,
            "RETRIEVAL_TOP_K": str(settings.retrieval_top_k),
            "CONFLUENCE_SEARCH_LIMIT": str(settings.confluence_search_limit),
            "MAX_PAGES_PER_QUERY": str(settings.max_pages_per_query),
            "CONFLUENCE_CACHE_TTL_SECONDS": str(settings.confluence_cache_ttl_seconds),
            "MAX_PAGE_CHARACTERS": str(settings.max_page_characters),
            "MAX_CHUNK_CHARACTERS": str(settings.max_chunk_characters),
            "OLLAMA_TIMEOUT_SECONDS": str(settings.ollama_timeout_seconds),
            "OLLAMA_RETRIES": str(settings.ollama_retries),
            "LOG_LEVEL": settings.log_level,
        }

        merged = dict(existing_values)
        merged.update(managed_values)

        ordered_keys = list(managed_values.keys())
        extra_keys = sorted(key for key in merged.keys() if key not in managed_values)
        lines = ["# Generated by VeriAgent dashboard setup", ""]

        for key in ordered_keys + extra_keys:
            lines.append(f"{key}={merged.get(key, '')}")

        env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
